### ISSUE TITLE
Inserting the Folder-Path

### ISSUE THREAD

**Issue by Jespermagician** [KeineSchere/Synch_Directorys#2]
*** Explaination of the issue***
When you edit the path at the beginning of the code, because you want to use it, you need to add a Backslash after adderssing the wantet directory (On Windows) or rather two because of the String handling

`r'C:\\ParentFolder\\ChildFolder\\` <- Does work

`r'C:\\ParentFolder\\ChildFolder` <- Doesn't work

***Request***
This isn't a really big issue, but it would be helpful to address it in the README.md or rather add the backslashes automaticly, if they arent added manualy

**Comment by KeineSchere** [comment]
Added for Version 1.1
